name: posbankum
description: Aplikasi Pos Bantuan Hukum Provinsi Riau
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  file_picker: ^8.1.4  # For file upload
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # State Management & Navigation
  get: ^4.6.6
  
  # Local Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  
  # UI & Animations
  animate_do: ^3.3.4
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  
  # Network & API
  dio: ^5.4.1
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  
  # Image & Media
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10
  
  # Form & Validation
  intl: ^0.19.0
  
  # Utils
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  
  # Loading & Dialogs
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  supabase_flutter: ^2.12.0
  google_sign_in: ^6.2.1
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/app_icon.png"
  # adaptive_icon_background: "#2B3A67"
  # adaptive_icon_foreground: "assets/images/logo/app_icon_foreground.png"

flutter:
  uses-material-design: true

  # Assets
  assets:
    # Logo
    - assets/images/logo/
    - assets/images/logo/logo_outline.png
    - assets/images/logo/logo_white.png
    - assets/images/logo/logo_full.png
    - assets/images/logo/logo_with_text.png
    
    # Onboarding
    - assets/images/onboarding/
    - assets/images/onboarding/onboarding_1.png
    - assets/images/onboarding/onboarding_2.png
    - assets/images/onboarding/onboarding_3.png
    
    # Icons & Illustrations
    - assets/images/icons/
    - assets/images/icons/building_illustration.png
    
    # Mascot
#    - assets/images/mascot/
    
    # Empty States
#    - assets/images/empty/
    
    # Placeholder
    - assets/images/placeholder.png
    - assets/images/avatar_placeholder.png

  # Fonts (uncomment jika pakai custom font)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
